dbType: oracle
servers:
  mysql:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://iruentech.cjyn70ttjgoq.ap-northeast-2.rds.amazonaws.com:3306/test?characterEncoding=utf8
    username: iruen
    password: iruen1111
  oracle:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.17:1521:ORCA
    username: test1
    password: test1
  redis:
    host: 127.0.0.1
    port: 6379
    max: 10
    timeout: 3000
    bolckwhenexhausted: true