dbType: mysql
servers:
  mysql:
    dirver: com.mysql.jdbc.Driver
    url: jdbc:mysql://iruentech.cjyn70ttjgoq.ap-northeast-2.rds.amazonaws.com:3306/test?characterEncoding=utf8
    username: iruen
    password: iruen1111
  oracle:
    dirver:
    url:
    username:
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    max: 10
    timeout: 3000
    bolckwhenexhausted: true